-- drop tables with constrains
DROP TABLE CATEGORY CASCADE CONSTRAINTS;
DROP TABLE ESHOP CASCADE CONSTRAINTS;
DROP TABLE GROUP_OF_PRODUCT CASCADE CONSTRAINTS;
DROP TABLE GROUP_PRODUCT CASCADE CONSTRAINTS;
DROP TABLE NEW_PRODUCT CASCADE CONSTRAINTS;
DROP TABLE PRODUCT CASCADE CONSTRAINTS;
DROP TABLE PRODUCT_IN_ESHOP CASCADE CONSTRAINTS;

-- drop sequences
DROP SEQUENCE CATEGORY_SEQ;
DROP SEQUENCE ESHOP_SEQ;
DROP SEQUENCE GROUP_OF_PRODUCT_SEQ;
DROP SEQUENCE NEW_PRODUCT_SEQ;
DROP SEQUENCE PRODUCT_IN_ESHOP_SEQ;
DROP SEQUENCE PRODUCT_SEQ;

-- create tables
CREATE TABLE CATEGORY (
    ID NUMBER(19,0) NOT NULL,
    NAME VARCHAR2(255 CHAR) NOT NULL,
    PARENT_CATEGORY_ID NUMBER(19,0),
    PRIMARY KEY (ID)
);

CREATE TABLE ESHOP (
    ID NUMBER(19,0) NOT NULL,
    ESHOP_TYPE VARCHAR2(255 CHAR),
    HOME_PAGE VARCHAR2(255 CHAR),
    NAME VARCHAR2(255 CHAR) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE GROUP_OF_PRODUCT (
    ID NUMBER(19,0) NOT NULL,
    NAME VARCHAR2(255 CHAR) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE GROUP_PRODUCT (
    GROUPID NUMBER(19,0) NOT NULL,
    PRODUCTID NUMBER(19,0) NOT NULL,
    GROUP_ID NUMBER(19,0),
    PRODUCT_ID NUMBER(19,0),
    PRIMARY KEY (GROUPID, PRODUCTID)
);

CREATE TABLE NEW_PRODUCT (
    ID NUMBER(19,0) NOT NULL,
    ESHOP_TYPE VARCHAR2(255 CHAR) NOT NULL,
    NAME VARCHAR2(255 CHAR) NOT NULL,
    PRODUCT_PICTURE_URL VARCHAR2(255 CHAR),
    PRODUCT_URL VARCHAR2(255 CHAR) NOT NULL,
    STATUS VARCHAR2(255 CHAR) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE PRODUCT (
    ID NUMBER(19,0) NOT NULL,
    COUNT_OF_ITEM_IN_ONE_PACKAGE INTEGER NOT NULL,
    COUNT_OF_UNIT DECIMAL(19,2) NOT NULL,
    GOOD_PRICE DECIMAL(19,2),
    IMAGE_PATH VARCHAR2(255 CHAR),
    NAME VARCHAR2(255 CHAR) NOT NULL,
    UNIT VARCHAR2(255 CHAR) NOT NULL,
    CATEGORY_ID NUMBER(19,0),
    PRIMARY KEY (ID)
);

CREATE TABLE PRODUCT_IN_ESHOP (
    ID NUMBER(19,0) NOT NULL,
    ACTION_VALID_TO TIMESTAMP,
    BEST_PRICE NUMBER(19,5),
    COUNT_OF_ITEM_IN_ONE_PACKAGE NUMBER(10,0) not null,
    COUNT_OF_UNIT NUMBER(19,5), NOT NULL,
    LAST_UPDATED_PRICE TIMESTAMP,
    PICTURE_EXIST NUMBER(1,0),
    PRICE_FOR_ONE_ITEM_IN_PAC NUMBER(19,5),
    PRICE_FOR_PACKAGE NUMBER(19,5),
    PRICE_FOR_UNIT NUMBER(19,5),
    PRODUCT_ACTION VARCHAR2(255 CHAR),
    PRODUCT_NAME_IN_ESHOP VARCHAR2(255 CHAR),
    PRODUCT_PAGE_IN_ESHOP VARCHAR2(255 CHAR) NOT NULL,
    PRODUCT_PICTURE_URL VARCHAR2(255 CHAR),
    UNIT VARCHAR2(255 CHAR) NOT NULL,
    UPDATE_STATUS VARCHAR2(255 CHAR),
    ESHOP_ID NUMBER(19,0) NOT NULL,
    PRODUCT_ID NUMBER(19,0) NOT NULL,
    PRIMARY KEY (ID)
);

-- unique constrains
ALTER TABLE CATEGORY ADD CONSTRAINT UQ_NAME  UNIQUE (NAME);
ALTER TABLE ESHOP ADD CONSTRAINT UQ_NAME  UNIQUE (NAME);
ALTER TABLE GROUP_OF_PRODUCT ADD CONSTRAINT UK_NAME  UNIQUE (NAME);
ALTER TABLE GROUP_PRODUCT ADD CONSTRAINT UK_GROUP_ID_PRODUCT_ID  UNIQUE (GROUP_ID, PRODUCT_ID);
ALTER TABLE NEW_PRODUCT ADD CONSTRAINT UK_PRODUCT_URL  UNIQUE (PRODUCT_URL);
ALTER TABLE PRODUCT ADD CONSTRAINT UK_NAME  UNIQUE (NAME);
ALTER TABLE PRODUCT_IN_ESHOP ADD CONSTRAINT UK_PRODUCT_PAGE_IN_ESHOP  UNIQUE (PRODUCT_PAGE_IN_ESHOP);

-- foreign constrains
ALTER TABLE CATEGORY
    ADD CONSTRAINT FK_PARENT_CATEGORY_ID
    FOREIGN KEY (PARENT_CATEGORY_ID)
    REFERENCES CATEGORY;

ALTER TABLE GROUP_PRODUCT
    ADD CONSTRAINT FK_PRODUCT_ID
    FOREIGN KEY (PRODUCT_ID)
    REFERENCES PRODUCT;

ALTER TABLE GROUP_PRODUCT
    ADD CONSTRAINT FK_GROUP_ID
    FOREIGN KEY (GROUP_ID)
    REFERENCES GROUP_OF_PRODUCT;

ALTER TABLE PRODUCT
    ADD CONSTRAINT FK_CATEGORY_ID
    FOREIGN KEY (CATEGORY_ID)
    REFERENCES CATEGORY;

ALTER TABLE PRODUCT_IN_ESHOP
    ADD CONSTRAINT FK_ESHOP_ID
    FOREIGN KEY (ESHOP_ID)
    REFERENCES ESHOP;

ALTER TABLE PRODUCT_IN_ESHOP
    ADD CONSTRAINT FK_PRODUCT_ID
    FOREIGN KEY (PRODUCT_ID)
    REFERENCES PRODUCT;

-- sequences
CREATE SEQUENCE CATEGORY_SEQ;
CREATE SEQUENCE ESHOP_SEQ;
CREATE SEQUENCE GROUP_OF_PRODUCT_SEQ;
CREATE SEQUENCE NEW_PRODUCT_SEQ;
CREATE SEQUENCE PRODUCT_IN_ESHOP_SEQ;
CREATE SEQUENCE PRODUCT_SEQ;

