ALTER TABLE product_in_eshop ALTER COLUMN PRICE_FOR_PACKAGE decimal(19,5);
ALTER TABLE product_in_eshop ALTER COLUMN PRICE_FOR_ONE_ITEM_IN_PAC decimal(19,5);
ALTER TABLE product_in_eshop ALTER COLUMN PRICE_FOR_UNIT decimal(19,5);
